//
//  StudentLocation.swift
//  On the Map
//
//  Created by Ivan Magda on 21.03.16.
//  Copyright © 2016 Ivan Magda. All rights reserved.
//

import Foundation
import UIKit

//------------------------------------
// MARK: - StudentLocation
//------------------------------------

struct StudentLocation {
    
    //------------------------------------
    // MARK: Properties
    //------------------------------------
    
    /// An auto-generated id/key generated by Parse which uniquely identifies a StudentLocation.
    let objectId: String
    
    /// Extra (optional) key used to uniquely identify a StudentLocation.
    let uniqueKey: String
    
    /// The first name of the student which matches their Udacity profile first name.
    let firstName: String
    
    /// The last name of the student which matches their Udacity profile last name.
    let lastName: String
    
    /// The location string used for geocoding the student location.
    let mapString: String
    
    /// The URL provided by the student.
    let mediaURL: NSURL
    
    /// The latitude of the student location (ranges from -90 to 90).
    let latitude: Float
    
    /// The longitude of the student location (ranges from -180 to 180).
    let longitude: Float
    
    /// The date when the student location was created.
    let createdAt: String
    
    /// The date when the student location was last updated.
    let updatedAt: String
    
    //------------------------------------
    // MARK: Initializers
    //------------------------------------
    
    init(objectId: String, uniqueKey: String, firstName: String, lastName: String, mapString: String,
        mediaURL: NSURL, latitude: Float, longitude: Float, createdAt: String, updatedAt: String) {
            self.objectId  = objectId
            self.uniqueKey = uniqueKey
            self.firstName = firstName
            self.lastName  = lastName
            self.mapString = mapString
            self.mediaURL  = mediaURL
            self.latitude  = latitude
            self.longitude = longitude
            self.createdAt = createdAt
            self.updatedAt = updatedAt
    }
    
    //------------------------------------
    // MARK: Methods
    //------------------------------------
    
    func openMediaURLInSafari() {
        let application = UIApplication.sharedApplication()
        
        if application.canOpenURL(mediaURL) {
            application.openURL(mediaURL)
        }
    }
    
    static func sanitizedStudentLocations(dicts: [[String: AnyObject]]?) -> [StudentLocation]? {
        guard let dicts = dicts else {
            return nil
        }
        
        return dicts.flatMap { StudentLocation.decode($0) }
    }
    
}